# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: tamvcspk.tgmirror
PackageVersion: 0.1.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tgmirror\tgmirror.exe
  PortableCommandAlias: tgmirror
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tamvcspk/tgmirror/releases/download/v0.1.1/tgmirror-0.1.1-windows-x64.zip
  InstallerSha256: 465E0F38A283E7024DC20403010492D20586099BA0B87795DD3D78DED28658DC
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-28
